version: '3.8'

services:
 vue:
    build: ./vue
    ports:
      - "5173:5173"
    volumes:
      - ./vue:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
 api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
